### ISSUE TITLE
Is it possible to disable creation of the file minim.conf with version number

### ISSUE THREAD

**Issue by project-owner** [bbye98/minim#18]
It appears in the user home folder after using the library. Is it really required?
Thanks!

**Comment by bbye98** [comment]
The configuration file stores access tokens and related information, should any API clients be instantiated with `save=True`. A blank file is always created when Minim is first imported.

**Comment by project-owner** [comment]
Yeah, that's the point - if I don't use any tokens why that file was created?
BTW, just to let you know that I've just released the new version of the Peppy player which leverages your library:
https://forums.raspberrypi.com/viewtopic.php?t=139983&start=525#p2226392

**Comment by bbye98** [comment]
It's fairly customary for software to have configuration file(s). Minim's configuration file is loaded at import so that account information can be read or written by the different API clients. There's no reason to complicate the codes for each of the separate API clients by having them check for a configuration file (and create one if it doesn't exist).

**Comment by project-owner** [comment]
Just trying to imagine that all 20 libraries which I use will start writing config files into user home :)
Right now you duplicate that code related to minim.cfg in all your clients. You can create a super class, put that and any other common code in that class and extend that class. Or if you prefer composition over inheritance just create a class which handles config file and use that class inside of each service class. Just another 2c.

**Comment by bbye98** [comment]
You're welcome to create your own fork of Minim to suit your specific needs, as long as you uphold the license that I've released Minim under.

As it stands right now, most software and libraries *do* create their own configuration files. Looking at my own WSL Ubuntu home directory, Bash, Conda, and Zsh (and even Python) have their own configuration/history files. Of course, they're all prepended with a `.` so it doesn't show up with a normal `ls` call. I chose to omit the `.` so that users can see and interact with the `minim.cfg` file should they choose so.

When you pip install a package, pip also leaves behind configuration files for each of the packages, albeit in their own directories in your Python installation's `pkgs` directory.

Even on Windows, software like Audacity, Discord, Fiddler, OneNote, etc. automatically generate folders to store configuration files in the `C:/Users/<username>/Documents` folder, with no way to disable this behavior.

You're trying to solve a problem that doesn't exist.
