### ISSUE TITLE
Future Plans, Collaboration, and Integration Questions

### ISSUE THREAD

**Issue by noctacode** [bbye98/minim#6]
Dear Benjamin,

I'm planning to develop a comprehensive music app.
I am happy to have discovered your library and am intending to incorporate it in my project.

The app would integrate several online sources and local files and it would include a local database of all account data (playlists, favourites, etc) and have several unique features.

I have some questions about minim so I can plan my development better.
1.  Is there a plan to integrate YouTube as well? And if not, would you help me extend your library with that capability?
2.  What's the general plan with minim? Will it be maintained actively indefinitely? What are your plans with it?
3.  Would you like to have a say in the design of my app? Since minim will be the backbone of it, I figure it'd make sense to include you, if that'd be of your interest, of course.

Thank you and kind regards,
Klemen

**Comment by bbye98** [comment]
Hi! Thanks for using Minim.

1. There are plans to integrate the YouTube Music API (see #4), but there's no concrete timeline for this. Unfortunately, the YouTube Music API is not standalone but rather bundled as part of the YouTube Data API, making it a bit more challenging to get right. 
2. As it stands currently, Minim--[originally meant to be a personal project/showcase that I open-sourced in the hopes that others may be able to take advantage of it](https://www.reddit.com/r/Python/comments/10kxmj9/deleted_by_user/j5vc3of/)--already serves all of my music library management needs. However, this does not necessarily mean development will stop. In fact, I've started working on implementing the Discogs API (that is compatible with the `minim.audio` submodule and comes with the features found in the other Minim APIs, like token caching), so you can expect this functionality in a few weeks. My general rationale moving forward is to prioritize the implementation of APIs with (comparatively) complete track metadata, like Deezer, Last.fm, and MusicBrainz, so that the premise of Minim being the one-stop-shop for tagging music still holds. Let me wrap up by saying that even should development stop, which I don't anticipate for quite a while, I will still respond to issues/questions and make pushes as necessary to fix bugs/glitches.
3. I'd like to limit my involvement to just Minim. As I am not a programmer by trade (just a hobbyist) and have no formal computer science training, I'm afraid I don't have enough time to take on more projects right now.

**Comment by bbye98** [comment]
@noctacode As I haven't heard back from you in a while, I'm going to go ahead and close this issue. Feel free to reopen it or create a new one if you have more questions!
