### ISSUE TITLE
Spotify Access token expired

### ISSUE THREAD

**Issue by ronajon** [bbye98/minim#7]
i'm trying to use Minim on a headless server, running a cron job for updating my dynamic Spotify playlists to Qobuz.
The authentication for Qobuz is working, but i'm experiencing issues with the Spotify Auth. 

how can i use the refresh token to generate a new access token when the old one expires? 

code i have so far, which allows me to update spotify to qobuz (but where the access token expires after 1 hour )

```
SPOTIFY_CLIENT_ID = "<spotify_clientid>"
SPOTIFY_CLIENT_SECRET = "<spotify_client_secret>"
SPOTIFY_ACCESS_TOKEN = "<spotify_access_token>"
SPOTIFY_REFRESH_TOKEN = "<spotify_refresh_token>"
SPOTIFY_REDIRECT_URL = "http://localhost:8888/callback"

scopes = spotify.WebAPI.get_scopes("all")
client_spotify = spotify.WebAPI(client_id=SPOTIFY_CLIENT_ID, client_secret=SPOTIFY_CLIENT_SECRET, flow="pkce",
                                scopes=scopes, web_framework="http.server")
```

using the access_token and refresh token in unfortunately does not work 

```
client_spotify = spotify.WebAPI(client_id=SPOTIFY_CLIENT_ID, client_secret=SPOTIFY_CLIENT_SECRET, flow="pkce",
                                scopes=scopes, web_framework="http.server", access_token=SPOTIFY_ACCESS_TOKEN, 
                                refresh_token=SPOTIFY_REFRESH_TOKEN, redirect_uri=SPOTIFY_REDIRECT_URL)
```

**Comment by bbye98** [comment]
If you provide all the necessary tokens (client credentials, access token, refresh token, etc.), it will persist as long as the `minim.spotify.WebAPI` object exists. However, I do not believe they get written to the Minim configuration file, which means you'll have to provide all the tokens each time you spin up your script. (This is by design since I can only ensure the credentials Minim writes to the configuration file are complete and valid.)

That being said, if you trust the machine you are running on and want to have your credentials persist through different executions of your script, you should create a/edit the file named `minim.cfg` in your home directory (whatever `pathlib.Path.home()` returns for your machine) and populate it with:

```
[minim]
version = 1.0.0

[minim.spotify.WebAPI]
flow = 
client_id = 
client_secret = 
access_token = 
expiry = 
refresh_token = 
scopes = 
redirect_uri = 
```

You should provide everything but the redirect URI since you are running headless. This setup will not only automatically reauthenticate you on subsequent instantiations of the `minim.spotify.WebAPI` class if your access token has expired, but also ensures that you don't accidentally try to reuse a refresh token you've already exchanged for another access token. (Plus, you can now call `client_spotify = minim.spotify.WebAPI()` with no parameters, and everything will be retrieved from the configuration file automatically.)

**Comment by ronajon** [comment]
thanks
that clarifies my issues.
perhaps it is some info that can be added to the docs ?
